services:
  app:
    build:
      context: ./app
    environment:
      - DATABASE_URL=mysql+pymysql://devuser:D3v_u53r#@54.176.167.84/COMPETENCIA
      - SECRET_KEY=DASHAUTO
    expose:
      - 7000
    volumes:
      - ./app:/app
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app

  platform:
    image: php:apache
    volumes:
      - ./platform:/var/www/html
    ports:
      - "8080:80"